### ISSUE TITLE
After changing config, generating duplicated cos_proxy_HostHealth_alert

### ISSUE THREAD

**Issue by xtrusia** [canonical/cos-proxy-operator#194]
### Bug Description

After changing config, too many alert_rules are generated.

TBD after testing further.

basically errors with nrpealert

### To Reproduce

1. juju deploy (cos) - bundle: https://paste.ubuntu.com/p/NVBGpYQrY3/
$ juju deploy ./bundle-cos -m myk8s-localhost:admin/cos --trust

2. juju deploy cos-proxy - bundle https://paste.ubuntu.com/p/srMbSbH6G3/
$ juju deploy ./bundle -m maas-default:admin/default


$ juju show-unit cos-proxy/0
```
relation-info:                           
- relation-id: 3                         
  endpoint: downstream-prometheus-scrape 
  cross-model: true                      
  related-endpoint: metrics-endpoint     
  application-data: {}                   
  related-units:                         
    prometheus/0:                        
      in-scope: true                     
      data:                              
        egress-subnets: 10.152.183.241/32
        ingress-address: 10.152.183.241  
        private-address: 10.152.183.241  
```

basically it is ok with simple alert_rules but when I change configuration. it suddenly has  a lot of info(as well as duplicated)

```
juju status (cos-proxy model)
Every 1.0s: juju status --relations --color                                                                                                tnode1: Mon Apr 14 23:08:59 2025
                                                                                                                                                                           
Model    Controller    Cloud/Region  Version  SLA          Timestamp                                                                                                       
default  maas-default  maas/default  2.9.51   unsupported  23:08:59Z                                                                                                       
                                                                                                                                                                           
SAAS                Status  Store            URL                                                                                                                           
grafana-dashboards  active  myk8s-localhost  admin/cos.grafana-dashboards                                                                                                  
prometheus          active  myk8s-localhost  admin/cos.prometheus                                                                                                          
                                                                                                                                                                           
App                       Version  Status   Scale  Charm                     Channel      Rev  Exposed  Message                                                            
cos-proxy                 n/a      active       1  cos-proxy                 latest/edge  138  no                                                                          
memcached                          error        1  memcached                 stable        39  no       hook failed: "local-monitors-relation-changed"                     
nagios                             waiting    0/1  nagios                    stable        63  no       waiting for machine                                                
nrpe                               blocked      2  nrpe                      stable       141  no       nagios-nrpe-server service inactive.                               
openstack-service-checks           blocked      1  openstack-service-checks  stable        56  no       Missing os-credentials vars: auth_url                              
telegraf                           active       1  telegraf                  stable        75  no       Monitoring openstack-service-checks/0 (source version/commit 23.10)
Unit                         Workload  Agent       Machine  Public address  Ports          Message                                                                         
cos-proxy/0*                 active    idle        1        10.0.0.3                                                                                                       
memcached/0*                 error     idle        3        10.0.0.16       11211/tcp      hook failed: "local-monitors-relation-changed" for nrpe:local-monitors          
  nrpe/0*                    blocked   idle                 10.0.0.16       icmp,5666/tcp  nagios-nrpe-server service inactive.                                            
nagios/0                     waiting   allocating  2        10.0.0.15                      waiting for machine                                                             
openstack-service-checks/0*  blocked   idle        0        10.0.0.14                      Missing os-credentials vars: auth_url                                           
  nrpe/1                     active    idle                 10.0.0.14       icmp,5666/tcp  Ready                                                                           
  telegraf/0*                active    idle                 10.0.0.14       9103/tcp       Monitoring openstack-service-checks/0 (source version/commit 23.10)             
                                                                                                                                                                           
Machine  State    Address    Inst id  Series  AZ       Message                                                                                                             
0        started  10.0.0.14  node-14  jammy   default  Deployed                                                                                                            
1        started  10.0.0.3   node-13  jammy   default  Deployed                                                                                                            
2        down     10.0.0.15  node-16  bionic  default  Failed deployment: Marking node failed - Node operation 'Deploying' timed out after 30 minutes.                     
3        started  10.0.0.16  node-18  jammy   default  Deployed                                                                                                            
                                                                                                                                                                           
Relation provider                              Requirer                     Interface              Type         Message                                                    
cos-proxy:downstream-prometheus-scrape         prometheus:metrics-endpoint  prometheus_scrape      regular                                                                 
memcached:cluster                              memcached:cluster            memcached-replication  peer                                                                    
memcached:juju-info                            nrpe:general-info            juju-info              subordinate                                                             
memcached:local-monitors                       nrpe:local-monitors          local-monitors         subordinate                                                             
memcached:monitors                             cos-proxy:monitors           monitors               regular                                                                 
memcached:nrpe-external-master                 nrpe:nrpe-external-master    nrpe-external-master   subordinate                                                             
nrpe:monitors                                  cos-proxy:monitors           monitors               regular                                                                 
nrpe:monitors                                  nagios:monitors              monitors               regular                                                                 
openstack-service-checks:juju-info             telegraf:juju-info           juju-info              subordinate                                                             
openstack-service-checks:nrpe-external-master  nrpe:nrpe-external-master    nrpe-external-master   subordinate                                                             
                                                                                                                                                                        
```

```
juju status (cos model)
Every 1.0s: juju status -m myk8s-localhost:cos --color --relations                                                                   

Model  Controller       Cloud/Region     Version  SLA          Timestamp
cos    myk8s-localhost  myk8s/localhost  3.4.5    unsupported  23:09:44Z

App           Version  Status  Scale  Charm             Channel        Rev  Address         Exposed  Message
alertmanager  0.27.0   active      1  alertmanager-k8s  latest/stable  156  10.152.183.164  no
catalogue              active      1  catalogue-k8s     latest/stable   81  10.152.183.101  no
grafana       9.5.3    active      1  grafana-k8s       latest/stable  139  10.152.183.159  no
loki          2.9.6    active      1  loki-k8s          latest/stable  187  10.152.183.31   no
prometheus    2.52.0   active      1  prometheus-k8s    latest/stable  232  10.152.183.49   no
traefik       2.11.0   active      1  traefik-k8s       latest/stable  234  10.152.183.37   no       Serving at 192.168.0.210

Unit             Workload  Agent  Address      Ports  Message
alertmanager/0*  active    idle   10.1.35.80
catalogue/0*     active    idle   10.1.35.76
grafana/0*       active    idle   10.1.35.98
loki/0*          active    idle   10.1.35.81
prometheus/0*    active    idle   10.1.35.65
traefik/0*       active    idle   10.1.35.119         Serving at 192.168.0.210

Offer                            Application  Charm           Rev  Connected  Endpoint              Interface                Role
grafana-dashboards               grafana      grafana-k8s     139  0/0        grafana-dashboard     grafana_dashboard        requirer
loki-logging                     loki         loki-k8s        187  0/0        logging               loki_push_api            provider
prometheus                       prometheus   prometheus-k8s  232  2/2        metrics-endpoint      prometheus_scrape        requirer
prometheus-receive-remote-write  prometheus   prometheus-k8s  232  0/0        receive-remote-write  prometheus_remote_write  provider

Relation provider                   Requirer                     Interface              Type     Message
alertmanager:alerting               loki:alertmanager            alertmanager_dispatch  regular
alertmanager:alerting               prometheus:alertmanager      alertmanager_dispatch  regular
alertmanager:grafana-dashboard      grafana:grafana-dashboard    grafana_dashboard      regular
alertmanager:grafana-source         grafana:grafana-source       grafana_datasource     regular
alertmanager:replicas               alertmanager:replicas        alertmanager_replica   peer
alertmanager:self-metrics-endpoint  prometheus:metrics-endpoint  prometheus_scrape      regular
catalogue:catalogue                 alertmanager:catalogue       catalogue              regular
catalogue:catalogue                 grafana:catalogue            catalogue              regular
catalogue:catalogue                 prometheus:catalogue         catalogue              regular
catalogue:replicas                  catalogue:replicas           catalogue_replica      peer
grafana:grafana                     grafana:grafana              grafana_peers          peer
grafana:metrics-endpoint            prometheus:metrics-endpoint  prometheus_scrape      regular
grafana:replicas                    grafana:replicas             grafana_replicas       peer
loki:grafana-dashboard              grafana:grafana-dashboard    grafana_dashboard      regular
loki:grafana-source                 grafana:grafana-source       grafana_datasource     regular
loki:metrics-endpoint               prometheus:metrics-endpoint  prometheus_scrape      regular
loki:replicas                       loki:replicas                loki_replica           peer
prometheus:grafana-dashboard        grafana:grafana-dashboard    grafana_dashboard      regular
prometheus:grafana-source           grafana:grafana-source       grafana_datasource     regular
prometheus:prometheus-peers         prometheus:prometheus-peers  prometheus_peers       peer
traefik:ingress                     alertmanager:ingress         ingress                regular
traefik:ingress                     catalogue:ingress            ingress                regular
traefik:ingress-per-unit            loki:ingress                 ingress_per_unit       regular
traefik:ingress-per-unit            prometheus:ingress           ingress_per_unit       regular
traefik:metrics-endpoint            prometheus:metrics-endpoint  prometheus_scrape      regular
traefik:peers                       traefik:peers                traefik_peers          peer
traefik:traefik-route               grafana:ingress              traefik_route          regular
```

![Image](https://github.com/user-attachments/assets/ba2339f7-68fd-43bf-b1d9-aa183b7153e3)

https://paste.ubuntu.com/p/qrRSgVC9hs/

has only one "default_xxxxxxxx_cos_proxy_HostHealth_alerts"

$ juju config cos-proxy nrpe_alert_on_warning=false

```
seyeongkim@tnode1:~/canonical/sf404769$ juju show-unit cos-proxy/0                     
cos-proxy/0:                                                                           
  workload-version: n/a                                                                
  machine: "1"                                                                         
  opened-ports: []                                                                     
  public-address: 10.0.0.14                                                            
  charm: ch:amd64/jammy/cos-proxy-138                                                  
  leader: true                                                                         
  life: alive                                                                          
  relation-info:                                                                       
  - relation-id: 3                                                                     
    endpoint: downstream-prometheus-scrape                                             
    cross-model: true                                                                  
    related-endpoint: metrics-endpoint                                                 
    application-data:                                                                  
      event: '{"errors": "error validating /tmp/tmpx71ka0ek/validate_rule.yaml: [425:3:
        groupname: \"default_4b1930ab_cos_proxy_HostHealth_alerts\" is repeated in     
        the same file"}'                                                               
    related-units:                                                                     
      prometheus/0:                                                                    
        in-scope: true                                                                 
        data:                                                                          
          egress-subnets: 10.152.183.241/32                                            
          ingress-address: 10.152.183.241                                              
          private-address: 10.152.183.241                                              
```

### alert_rules
https://paste.ubuntu.com/p/QfvrpyCsCP/

there are two default_4b1930ab_cos_proxy_HostHealth_alerts so error.

### Environment

latest/edge

### Relevant log output

```shell
https://paste.ubuntu.com/p/zYJQvGRyjP/


  workload-version: n/a                                                                
  machine: "1"                                                                         
  opened-ports: []                                                                     
  public-address: 10.0.0.3                                                             
  charm: ch:amd64/jammy/cos-proxy-138                                                  
  leader: true                                                                         
  life: alive                                                                          
  relation-info:                                                                       
  - relation-id: 10                                                                    
    endpoint: downstream-prometheus-scrape                                             
    cross-model: true                                                                  
    related-endpoint: metrics-endpoint                                                 
    application-data:                                                                  
      event: '{"errors": "error validating /tmp/tmpzeho4coe/validate_rule.yaml: [225:3:
        groupname: \"default_60216322_cos_proxy_HostHealth_alerts\" is repeated in     
        the same file"}'                                                               
    related-units:                                                                     
      prometheus/0:                                                                    
        in-scope: true                                                                 
        data:                                                                          
          egress-subnets: 10.152.183.49/32                                             
          ingress-address: 10.152.183.49                                               
          private-address: 10.152.183.49
```

### Additional context

_No response_
