### ISSUE TITLE
Prometheus alerts not cleared

### ISSUE THREAD

**Issue by selcem-artan** [canonical/cos-proxy-operator#196]
### Bug Description

In an environment with COS we are receiving "FIRING" state alerts in prometheus. For these alerts when we check on the target node, status of service do not reflect the alerts. Below are examples;
- We receive "CheckRebootNrpeAlert" alert still in FIRING state and when we check node it does not have reboot_required or we tried to run "ack-reboot" action also which does not clear alert
- Also crm status alerts, which shows Health OK as a false alert.

![Image](https://github.com/user-attachments/assets/86cd2f8b-1fa7-4028-8712-db1294edf642)

![Image](https://github.com/user-attachments/assets/1cbb3dcf-b562-4fe6-a25f-98f1924e16ea)

### To Reproduce

With openstack deployed;
juju deploy traefik
juju deploy alertmanager
juju deploy prometheus
juju deploy grafana
juju deploy catalogue
juju deploy loki

```
$ juju status --relations -m microk8s-controller:cos
Model  Controller           Cloud/Region              Version  SLA          Timestamp
cos    microk8s-controller  microk8s_cloud/localhost  3.6.4    unsupported  09:43:53Z

App                     Version  Status  Scale  Charm                         Channel        Rev  Address         Exposed  Message
alertmanager            0.27.0   active      1  alertmanager-k8s              latest/stable  156  10.152.183.248  no       
catalogue                        active      1  catalogue-k8s                 latest/stable   81  10.152.183.169  no       
grafana                 9.5.3    active      1  grafana-k8s                   latest/stable  139  10.152.183.27   no       
loki                    2.9.6    active      1  loki-k8s                      latest/stable  187  10.152.183.135  no       
prometheus              2.52.0   active      1  prometheus-k8s                latest/stable  232  10.152.183.246  no       
scrape-interval-config  n/a      active      1  prometheus-scrape-config-k8s  latest/stable   58  10.152.183.141  no       
traefik                 2.11.0   active      1  traefik-k8s                   latest/stable  234  10.152.183.111  no       Serving at 10.250.136.22

Unit                       Workload  Agent  Address       Ports  Message
alertmanager/0*            active    idle   10.1.35.138          
catalogue/0*               active    idle   10.1.100.137         
grafana/0*                 active    idle   10.1.100.140         
loki/0*                    active    idle   10.1.151.72          
prometheus/0*              active    idle   10.1.35.139          
scrape-interval-config/0*  active    idle   10.1.151.70          
traefik/0*                 active    idle   10.1.100.139         Serving at 10.250.136.22

Offer                   Application             Charm                         Rev  Connected  Endpoint                  Interface                Role
alertmanager            alertmanager            alertmanager-k8s              156  0/0        karma-dashboard           karma_dashboard          provider
grafana                 grafana                 grafana-k8s                   139  4/4        grafana-dashboard         grafana_dashboard        requirer
loki                    loki                    loki-k8s                      187  3/3        logging                   loki_push_api            provider
prometheus              prometheus              prometheus-k8s                232  3/3        metrics-endpoint          prometheus_scrape        requirer
                                                                                              receive-remote-write      prometheus_remote_write  provider
scrape-interval-config  scrape-interval-config  prometheus-scrape-config-k8s  58   2/2        configurable-scrape-jobs  prometheus_scrape        requirer

Integration provider                     Requirer                     Interface              Type     Message
alertmanager:alerting                    loki:alertmanager            alertmanager_dispatch  regular  
alertmanager:alerting                    prometheus:alertmanager      alertmanager_dispatch  regular  
alertmanager:grafana-dashboard           grafana:grafana-dashboard    grafana_dashboard      regular  
alertmanager:grafana-source              grafana:grafana-source       grafana_datasource     regular  
alertmanager:replicas                    alertmanager:replicas        alertmanager_replica   peer     
alertmanager:self-metrics-endpoint       prometheus:metrics-endpoint  prometheus_scrape      regular  
catalogue:catalogue                      alertmanager:catalogue       catalogue              regular  
catalogue:catalogue                      grafana:catalogue            catalogue              regular  
catalogue:catalogue                      prometheus:catalogue         catalogue              regular  
catalogue:replicas                       catalogue:replicas           catalogue_replica      peer     
grafana:grafana                          grafana:grafana              grafana_peers          peer     
grafana:metrics-endpoint                 prometheus:metrics-endpoint  prometheus_scrape      regular  
grafana:replicas                         grafana:replicas             grafana_replicas       peer     
loki:grafana-dashboard                   grafana:grafana-dashboard    grafana_dashboard      regular  
loki:grafana-source                      grafana:grafana-source       grafana_datasource     regular  
loki:metrics-endpoint                    prometheus:metrics-endpoint  prometheus_scrape      regular  
loki:replicas                            loki:replicas                loki_replica           peer     
prometheus:grafana-dashboard             grafana:grafana-dashboard    grafana_dashboard      regular  
prometheus:grafana-source                grafana:grafana-source       grafana_datasource     regular  
prometheus:prometheus-peers              prometheus:prometheus-peers  prometheus_peers       peer     
scrape-interval-config:metrics-endpoint  prometheus:metrics-endpoint  prometheus_scrape      regular  
traefik:ingress                          alertmanager:ingress         ingress                regular  
traefik:ingress                          catalogue:ingress            ingress                regular  
traefik:ingress-per-unit                 loki:ingress                 ingress_per_unit       regular  
traefik:ingress-per-unit                 prometheus:ingress           ingress_per_unit       regular  
traefik:metrics-endpoint                 prometheus:metrics-endpoint  prometheus_scrape      regular  
traefik:peers                            traefik:peers                traefik_peers          peer     
traefik:traefik-route                    grafana:ingress              traefik_route          regular 
```

### Environment

Openstack Jammy/Yoga and and microk8s  1.28.15

### Relevant log output

```shell
From alert-manager pod we receive below logs;
2025-04-16T09:47:42.353Z [container-agent] 2025-04-16 09:47:42 WARNING juju-log <class '__main__.AlertmanagerCharm'>._charm_tracing_ca_cert is None; sending traces over INSECURE connection.
2025-04-16T09:47:43.082Z [container-agent] 2025-04-16 09:47:43 ERROR juju-log Failed to obtain status: Bad response
2025-04-16T09:47:43.294Z [container-agent] 2025-04-16 09:47:43 INFO juju-log HTTP Request: GET https://10.152.183.1/apis/apps/v1/namespaces/cos/statefulsets/alertmanager "HTTP/1.1 200 OK"
2025-04-16T09:47:43.459Z [container-agent] 2025-04-16 09:47:43 INFO juju-log HTTP Request: GET https://10.152.183.1/api/v1/namespaces/cos/pods/alertmanager-0 "HTTP/1.1 200 OK"
2025-04-16T09:47:46.012Z [container-agent] 2025-04-16 09:47:46 WARNING juju-log config reload via HTTP POST failed: Bad response
2025-04-16T09:47:46.027Z [container-agent] 2025-04-16 09:47:46 INFO juju-log Restarting service alertmanager
2025-04-16T09:47:47.373Z [container-agent] 2025-04-16 09:47:47 WARNING juju-log charm tracing buffer exceeds max history length (100 events)
2025-04-16T09:47:47.837Z [container-agent] 2025-04-16 09:47:47 WARNING juju-log cannot determine if reload succeeded
2025-04-16T09:47:47.986Z [container-agent] 2025-04-16 09:47:47 WARNING juju-log charm tracing buffer exceeds max history length (100 events)
2025-04-16T09:47:48.313Z [container-agent] 2025-04-16 09:47:48 INFO juju.worker.uniter.operation runhook.go:186 ran "update-status" hook (via hook dispatching script: dispatch)
```

**Comment by aym-frikha** [comment]
I also saw logs about service alertmanager stopped in the pod:

`ubuntu@microk8s-1:~$ microk8s.kubectl logs alertmanager-0 -n cos -c alertmanager | grep stopped
2025-04-16T04:21:56.076Z [pebble] Service "alertmanager" stopped
2025-04-16T04:26:26.477Z [pebble] Service "alertmanager" stopped
2025-04-16T04:32:14.136Z [pebble] Service "alertmanager" stopped
2025-04-16T04:37:35.390Z [pebble] Service "alertmanager" stopped
2025-04-16T04:42:33.481Z [pebble] Service "alertmanager" stopped
2025-04-16T04:47:44.685Z [pebble] Service "alertmanager" stopped
2025-04-16T04:53:42.926Z [pebble] Service "alertmanager" stopped
2025-04-16T04:59:00.715Z [pebble] Service "alertmanager" stopped
2025-04-16T05:04:39.452Z [pebble] Service "alertmanager" stopped
2025-04-16T05:08:47.837Z [pebble] Service "alertmanager" stopped
2025-04-16T05:14:01.843Z [pebble] Service "alertmanager" stopped
2025-04-16T05:19:46.711Z [pebble] Service "alertmanager" stopped
2025-04-16T05:25:31.117Z [pebble] Service "alertmanager" stopped
2025-04-16T05:29:55.830Z [pebble] Service "alertmanager" stopped
2025-04-16T05:35:40.051Z [pebble] Service "alertmanager" stopped
2025-04-16T05:41:04.316Z [pebble] Service "alertmanager" stopped
2025-04-16T05:45:59.276Z [pebble] Service "alertmanager" stopped
2025-04-16T05:50:08.416Z [pebble] Service "alertmanager" stopped
2025-04-16T05:54:17.026Z [pebble] Service "alertmanager" stopped
2025-04-16T06:00:15.944Z [pebble] Service "alertmanager" stopped
2025-04-16T06:06:15.535Z [pebble] Service "alertmanager" stopped
2025-04-16T06:11:31.577Z [pebble] Service "alertmanager" stopped
2025-04-16T06:17:31.174Z [pebble] Service "alertmanager" stopped
2025-04-16T06:23:16.382Z [pebble] Service "alertmanager" stopped
2025-04-16T06:28:18.130Z [pebble] Service "alertmanager" stopped
2025-04-16T06:33:43.580Z [pebble] Service "alertmanager" stopped
2025-04-16T06:39:00.266Z [pebble] Service "alertmanager" stopped
2025-04-16T06:43:19.371Z [pebble] Service "alertmanager" stopped
2025-04-16T06:48:59.938Z [pebble] Service "alertmanager" stopped
2025-04-16T06:54:23.270Z [pebble] Service "alertmanager" stopped
2025-04-16T06:59:11.708Z [pebble] Service "alertmanager" stopped
2025-04-16T07:04:51.537Z [pebble] Service "alertmanager" stopped
2025-04-16T07:09:08.001Z [pebble] Service "alertmanager" stopped
2025-04-16T07:14:40.830Z [pebble] Service "alertmanager" stopped
2025-04-16T07:19:06.929Z [pebble] Service "alertmanager" stopped
2025-04-16T07:23:47.892Z [pebble] Service "alertmanager" stopped
2025-04-16T07:29:38.936Z [pebble] Service "alertmanager" stopped
2025-04-16T07:34:51.023Z [pebble] Service "alertmanager" stopped
2025-04-16T07:39:26.016Z [pebble] Service "alertmanager" stopped
2025-04-16T07:43:46.918Z [pebble] Service "alertmanager" stopped
2025-04-16T07:48:20.923Z [pebble] Service "alertmanager" stopped
2025-04-16T07:52:22.417Z [pebble] Service "alertmanager" stopped
2025-04-16T07:56:27.945Z [pebble] Service "alertmanager" stopped
2025-04-16T08:00:41.047Z [pebble] Service "alertmanager" stopped
2025-04-16T08:06:25.052Z [pebble] Service "alertmanager" stopped
2025-04-16T08:10:41.134Z [pebble] Service "alertmanager" stopped
2025-04-16T08:16:29.293Z [pebble] Service "alertmanager" stopped
2025-04-16T08:21:29.140Z [pebble] Service "alertmanager" stopped
2025-04-16T08:26:43.521Z [pebble] Service "alertmanager" stopped
2025-04-16T08:31:37.561Z [pebble] Service "alertmanager" stopped
2025-04-16T08:37:09.583Z [pebble] Service "alertmanager" stopped
2025-04-16T08:41:56.832Z [pebble] Service "alertmanager" stopped
2025-04-16T08:47:32.187Z [pebble] Service "alertmanager" stopped
2025-04-16T08:51:56.131Z [pebble] Service "alertmanager" stopped
2025-04-16T08:57:55.734Z [pebble] Service "alertmanager" stopped
2025-04-16T09:02:56.355Z [pebble] Service "alertmanager" stopped
2025-04-16T09:07:02.894Z [pebble] Service "alertmanager" stopped
2025-04-16T09:11:49.096Z [pebble] Service "alertmanager" stopped
2025-04-16T09:17:28.795Z [pebble] Service "alertmanager" stopped
2025-04-16T09:22:18.612Z [pebble] Service "alertmanager" stopped
2025-04-16T09:28:02.363Z [pebble] Service "alertmanager" stopped
2025-04-16T09:33:04.427Z [pebble] Service "alertmanager" stopped
2025-04-16T09:38:26.452Z [pebble] Service "alertmanager" stopped
2025-04-16T09:43:39.439Z [pebble] Service "alertmanager" stopped
2025-04-16T09:47:46.213Z [pebble] Service "alertmanager" stopped
2025-04-16T09:53:25.534Z [pebble] Service "alertmanager" stopped`

**Comment by selcem-artan** [comment]
[juju_status_openstack.txt](https://github.com/user-attachments/files/19775029/juju_status_openstack.txt)

[openstack.bundle.txt](https://github.com/user-attachments/files/19775033/openstack.bundle.txt)

**Comment by selcem-artan** [comment]
COS bundle 
`bundle: kubernetes
saas:
  remote-1e0b5fba974b4dc285ffba8ecdc83024: {}
  remote-25e8bf0fa50646ad8b62b2b8e13ab5c7: {}
  remote-92db1265c9a347dc875b0930d03a0fb1: {}
  remote-659341edbab74d5187872cce7a6f3430: {}
  remote-a5615f97d361472a89f7a1064226ec11: {}
applications:
  alertmanager:
    charm: alertmanager-k8s
    channel: latest/stable
    revision: 156
    resources:
      alertmanager-image: 99
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,20480M
    trust: true
  catalogue:
    charm: catalogue-k8s
    channel: latest/stable
    revision: 81
    resources:
      catalogue-image: 34
    scale: 1
    options:
      description: |
        Canonical Observability Stack Lite, or COS Lite, is a light-weight, highly-integrated,
        Juju-based observability suite running on Kubernetes.
      tagline: Model-driven Observability Stack deployed with a single command.
      title: Netlogix Canonical Observability Stack
    constraints: arch=amd64
    trust: true
  grafana:
    charm: grafana-k8s
    channel: latest/stable
    revision: 139
    resources:
      grafana-image: 71
      litestream-image: 46
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,20480M
    trust: true
  loki:
    charm: loki-k8s
    channel: latest/stable
    revision: 187
    resources:
      loki-image: 100
      node-exporter-image: 3
    scale: 1
    constraints: arch=amd64
    storage:
      active-index-directory: kubernetes,1,2048M
      loki-chunks: kubernetes,1,184320M
    trust: true
  prometheus:
    charm: prometheus-k8s
    channel: latest/stable
    revision: 232
    resources:
      prometheus-image: 151
    scale: 1
    options:
      metrics_retention_time: 62d
    constraints: arch=amd64
    storage:
      database: kubernetes,1,184320M
    trust: true
  scrape-interval-config:
    charm: prometheus-scrape-config-k8s
    channel: latest/stable
    revision: 58
    scale: 1
    options:
      scrape_interval: 5m
      scrape_timeout: 30s
    constraints: arch=amd64
    trust: true
  traefik:
    charm: traefik-k8s
    channel: latest/stable
    revision: 234
    resources:
      traefik-image: 161
    scale: 1
    constraints: arch=amd64
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - traefik:ingress-per-unit
  - prometheus:ingress
- - traefik:ingress-per-unit
  - loki:ingress
- - traefik:traefik-route
  - grafana:ingress
- - traefik:ingress
  - alertmanager:ingress
- - prometheus:alertmanager
  - alertmanager:alerting
- - grafana:grafana-source
  - prometheus:grafana-source
- - grafana:grafana-source
  - loki:grafana-source
- - grafana:grafana-source
  - alertmanager:grafana-source
- - loki:alertmanager
  - alertmanager:alerting
- - prometheus:metrics-endpoint
  - traefik:metrics-endpoint
- - prometheus:metrics-endpoint
  - alertmanager:self-metrics-endpoint
- - prometheus:metrics-endpoint
  - loki:metrics-endpoint
- - prometheus:metrics-endpoint
  - grafana:metrics-endpoint
- - grafana:grafana-dashboard
  - loki:grafana-dashboard
- - grafana:grafana-dashboard
  - prometheus:grafana-dashboard
- - grafana:grafana-dashboard
  - alertmanager:grafana-dashboard
- - catalogue:ingress
  - traefik:ingress
- - catalogue:catalogue
  - grafana:catalogue
- - catalogue:catalogue
  - prometheus:catalogue
- - catalogue:catalogue
  - alertmanager:catalogue
- - prometheus:receive-remote-write
  - remote-92db1265c9a347dc875b0930d03a0fb1:send-remote-write
- - grafana:grafana-dashboard
  - remote-92db1265c9a347dc875b0930d03a0fb1:grafana-dashboards-provider
- - prometheus:receive-remote-write
  - remote-25e8bf0fa50646ad8b62b2b8e13ab5c7:send-remote-write
- - loki:logging
  - remote-92db1265c9a347dc875b0930d03a0fb1:logging-consumer
- - grafana:grafana-dashboard
  - remote-25e8bf0fa50646ad8b62b2b8e13ab5c7:grafana-dashboards-provider
- - prometheus:receive-remote-write
  - remote-659341edbab74d5187872cce7a6f3430:send-remote-write
- - grafana:grafana-dashboard
  - remote-659341edbab74d5187872cce7a6f3430:grafana-dashboards-provider
- - loki:logging
  - remote-25e8bf0fa50646ad8b62b2b8e13ab5c7:logging-consumer
- - loki:logging
  - remote-659341edbab74d5187872cce7a6f3430:logging-consumer
- - grafana:grafana-dashboard
  - remote-a5615f97d361472a89f7a1064226ec11:downstream-grafana-dashboard
- - scrape-interval-config:configurable-scrape-jobs
  - remote-a5615f97d361472a89f7a1064226ec11:downstream-prometheus-scrape
- - scrape-interval-config:configurable-scrape-jobs
  - remote-1e0b5fba974b4dc285ffba8ecdc83024:downstream-prometheus-scrape
- - scrape-interval-config:metrics-endpoint
  - prometheus:metrics-endpoint
--- # overlay.yaml
applications:
  alertmanager:
    offers:
      alertmanager:
        endpoints:
        - karma-dashboard
        acl:
          admin: admin
  grafana:
    offers:
      grafana:
        endpoints:
        - grafana-dashboard
        acl:
          admin: admin
  loki:
    offers:
      loki:
        endpoints:
        - logging
        acl:
          admin: admin
  prometheus:
    offers:
      prometheus:
        endpoints:
        - metrics-endpoint
        - receive-remote-write
        acl:
          admin: admin
  scrape-interval-config:
    offers:
      scrape-interval-config:
        endpoints:
        - configurable-scrape-jobs
        acl:
          admin: admin
`

**Comment by sed-i** [comment]
@selcem-artan reposting after redaction

```yaml
bundle: kubernetes
applications:
  alertmanager:
    charm: alertmanager-k8s
    channel: latest/stable
    revision: 156
    resources:
      alertmanager-image: 99
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,20480M
    trust: true
  catalogue:
    charm: catalogue-k8s
    channel: latest/stable
    revision: 81
    resources:
      catalogue-image: 34
    scale: 1
    options:
      description: |
        Canonical Observability Stack Lite, or COS Lite, is a light-weight, highly-integrated,
        Juju-based observability suite running on Kubernetes.
      tagline: Model-driven Observability Stack deployed with a single command.
      title: Canonical Observability Stack
    constraints: arch=amd64
    trust: true
  grafana:
    charm: grafana-k8s
    channel: latest/stable
    revision: 139
    resources:
      grafana-image: 71
      litestream-image: 46
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,20480M
    trust: true
  loki:
    charm: loki-k8s
    channel: latest/stable
    revision: 187
    resources:
      loki-image: 100
      node-exporter-image: 3
    scale: 1
    constraints: arch=amd64
    storage:
      active-index-directory: kubernetes,1,2048M
      loki-chunks: kubernetes,1,184320M
    trust: true
  prometheus:
    charm: prometheus-k8s
    channel: latest/stable
    revision: 232
    resources:
      prometheus-image: 151
    scale: 1
    options:
      metrics_retention_time: 62d
    constraints: arch=amd64
    storage:
      database: kubernetes,1,184320M
    trust: true
  scrape-interval-config:
    charm: prometheus-scrape-config-k8s
    channel: latest/stable
    revision: 58
    scale: 1
    options:
      scrape_interval: 5m
      scrape_timeout: 30s
    constraints: arch=amd64
    trust: true
  traefik:
    charm: traefik-k8s
    channel: latest/stable
    revision: 234
    resources:
      traefik-image: 161
    scale: 1
    constraints: arch=amd64
    storage:
      configurations: kubernetes,1,1024M
    trust: true
relations:
- - traefik:ingress-per-unit
  - prometheus:ingress
- - traefik:ingress-per-unit
  - loki:ingress
- - traefik:traefik-route
  - grafana:ingress
- - traefik:ingress
  - alertmanager:ingress
- - prometheus:alertmanager
  - alertmanager:alerting
- - grafana:grafana-source
  - prometheus:grafana-source
- - grafana:grafana-source
  - loki:grafana-source
- - grafana:grafana-source
  - alertmanager:grafana-source
- - loki:alertmanager
  - alertmanager:alerting
- - prometheus:metrics-endpoint
  - traefik:metrics-endpoint
- - prometheus:metrics-endpoint
  - alertmanager:self-metrics-endpoint
- - prometheus:metrics-endpoint
  - loki:metrics-endpoint
- - prometheus:metrics-endpoint
  - grafana:metrics-endpoint
- - grafana:grafana-dashboard
  - loki:grafana-dashboard
- - grafana:grafana-dashboard
  - prometheus:grafana-dashboard
- - grafana:grafana-dashboard
  - alertmanager:grafana-dashboard
- - catalogue:ingress
  - traefik:ingress
- - catalogue:catalogue
  - grafana:catalogue
- - catalogue:catalogue
  - prometheus:catalogue
- - catalogue:catalogue
  - alertmanager:catalogue
- - scrape-interval-config:metrics-endpoint
  - prometheus:metrics-endpoint
--- # overlay.yaml
applications:
  alertmanager:
    offers:
      alertmanager:
        endpoints:
        - karma-dashboard
        acl:
          admin: admin
  grafana:
    offers:
      grafana:
        endpoints:
        - grafana-dashboard
        acl:
          admin: admin
  loki:
    offers:
      loki:
        endpoints:
        - logging
        acl:
          admin: admin
  prometheus:
    offers:
      prometheus:
        endpoints:
        - metrics-endpoint
        - receive-remote-write
        acl:
          admin: admin
  scrape-interval-config:
    offers:
      scrape-interval-config:
        endpoints:
        - configurable-scrape-jobs
        acl:
          admin: admin
```

**Comment by sed-i** [comment]
Summary of troubleshooting with @selcem-artan:

The scrape jobs for the NRPE metrics reach prometheus, but they are not written to prometheus config file (`/etc/prometheus/config.yml`) because they [fail validation](https://github.com/canonical/prometheus-k8s-operator/blob/610f9703a85f58f2eeeb34a6f44fb1811f0f0ba8/lib/charms/prometheus_k8s/v0/prometheus_scrape.py#L2375) with cos-tool:

```
unit-prometheus-0: 17:21:13 ERROR unit.prometheus/0.juju-log metrics-endpoint:27: Validating scrape jobs failed: b'time="2025-04-10T17:21:13Z" level=fatal msg="parsing YAML file /tmp/tmp5xmzn3rd: yaml: unmarshal errors:
  line 2: field forward_alert_rules not found in type config.ScrapeConfig
  line 46: field forward_alert_rules not found in type config.ScrapeConfig
  line 90: field forward_alert_rules not found in type config.ScrapeConfig
  line 134: field forward_alert_rules not found in type config.ScrapeConfig
  line 178: field forward_alert_rules not found in type config.ScrapeConfig
  line 222: field forward_alert_rules not found in type config.ScrapeConfig
  line 266: field forward_alert_rules not found in type config.ScrapeConfig
  line 310: field forward_alert_rules not found in type config.ScrapeConfig
  line 354: field forward_alert_rules not found in type config.ScrapeConfig
  line 398: field forward_alert_rules not found in type config.ScrapeConfig
  line 442: field forward_alert_rules not found in type config.ScrapeConfig
  line 486: field forward_alert_rules not found in type config.ScrapeConfig
  line 530: field forward_alert_rules not found in type config.ScrapeConfig
  line 574: field forward_alert_rules not found in type config.ScrapeConfig
  line 618: field forward_alert_rules not found in type config.ScrapeConfig
  line 662: field forward_alert_rules not found in type config.ScrapeConfig
```

**Comment by sed-i** [comment]
## Reproducer

### Bundle for "cos" model

```yaml
bundle: kubernetes
saas:
  remote-591bef2881d2472f8c0965ac281935db: {}
applications:
  prometheus:
    charm: prometheus-k8s
    channel: latest/stable
    revision: 232
    resources:
      prometheus-image: 151
    scale: 1
    options:
      metrics_retention_time: 62d
    constraints: arch=amd64
    storage:
      database: kubernetes,1,184320M
    trust: true
  scrape-interval-config:
    charm: prometheus-scrape-config-k8s
    channel: latest/stable
    revision: 58
    scale: 1
    options:
      scrape_interval: 5m
      scrape_timeout: 30s
    constraints: arch=amd64
    trust: true
relations:
- - scrape-interval-config:configurable-scrape-jobs
  - remote-591bef2881d2472f8c0965ac281935db:downstream-prometheus-scrape
- - prometheus:metrics-endpoint
  - scrape-interval-config:metrics-endpoint
--- # overlay.yaml
applications:
  prometheus:
    offers:
      prometheus:
        endpoints:
        - metrics-endpoint
        - receive-remote-write
        acl:
          admin: admin
  scrape-interval-config:
    offers:
      scrape-interval-config:
        endpoints:
        - configurable-scrape-jobs
        acl:
          admin: admin
```

### Bundle for lxd model
```yaml
saas:
  scrape-interval-config:
    url: microk8s:admin/cos.scrape-interval-config
applications:
  cp:
    charm: cos-proxy
    channel: latest/stable
    revision: 134
    base: ubuntu@20.04/stable
    num_units: 1
    to:
    - "8"
    constraints: arch=amd64
  nrpe:
    charm: nrpe
    channel: latest/edge
    revision: 155
    base: ubuntu@22.04/stable
  ub:
    charm: ubuntu
    channel: latest/stable
    revision: 25
    base: ubuntu@22.04/stable
    num_units: 1
    to:
    - "9"
    constraints: arch=amd64
    storage:
      block: loop,100M
      files: rootfs,100M
machines:
  "8":
    constraints: arch=amd64
    base: ubuntu@20.04/stable
  "9":
    constraints: arch=amd64
    base: ubuntu@22.04/stable
relations:
- - nrpe:monitors
  - cp:monitors
- - ub:juju-info
  - nrpe:general-info
- - cp:downstream-prometheus-scrape
  - scrape-interval-config:configurable-scrape-jobs
```


## The issue

The scrape job that reached prometheus has a `forward_alert_rules` key in every scrape config:

```yaml
scrape_configs:
- forward_alert_rules: true
  job_name: juju_welcome-lxd_7f841a7_ub_0_check_conntrack_prometheus_scrape
  metrics_path: /export
  params:
    command:
    - check_conntrack
    ssl:
    - true
  relabel_configs:
  - regex: (.*)
    separator: _
    source_labels:
    - juju_model
    - juju_model_uuid
    - juju_application
    - juju_unit
    target_label: instance
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - source_labels:
    - __param_command
    target_label: command
  - replacement: 10.5.66.4:9275
    target_label: __address__
  - replacement: ub/0
    target_label: juju_unit
  - replacement: ub
    target_label: juju_application
  scrape_interval: 5m
  scrape_timeout: 30s
  static_configs:
  - labels:
      dns_name: juju-0a9b90-9.lxd
      host: 10.5.66.251
      juju_application: nrpe
      juju_model: welcome-lxd
      juju_model_uuid: 7f841a78-278e-4f12-8a42-688d600a9b90
      juju_unit: nrpe/0
    targets:
    - 10.5.66.251:5666
- forward_alert_rules: true
  job_name: juju_welcome-lxd_7f841a7_ub_0_check_systemd_scopes_prometheus_scrape
  metrics_path: /export
  params:
    command:
    - check_systemd_scopes
    ssl:
    - true
  relabel_configs:
  - regex: (.*)
    separator: _
    source_labels:
    - juju_model
    - juju_model_uuid
    - juju_application
    - juju_unit
    target_label: instance
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - source_labels:
    - __param_command
    target_label: command
  - replacement: 10.5.66.4:9275
    target_label: __address__
  - replacement: ub/0
    target_label: juju_unit
  - replacement: ub
    target_label: juju_application
  scrape_interval: 5m
  scrape_timeout: 30s
  static_configs:
  - labels:
      dns_name: juju-0a9b90-9.lxd
      host: 10.5.66.251
      juju_application: nrpe
      juju_model: welcome-lxd
      juju_model_uuid: 7f841a78-278e-4f12-8a42-688d600a9b90
      juju_unit: nrpe/0
    targets:
    - 10.5.66.251:5666
- forward_alert_rules: true
  job_name: juju_welcome-lxd_7f841a7_ub_0_check_reboot_prometheus_scrape
  metrics_path: /export
  params:
    command:
    - check_reboot
    ssl:
    - true
  relabel_configs:
  - regex: (.*)
    separator: _
    source_labels:
    - juju_model
    - juju_model_uuid
    - juju_application
    - juju_unit
    target_label: instance
  - source_labels:
    - __address__
    target_label: __param_target
  - source_labels:
    - __param_target
    target_label: instance
  - source_labels:
    - __param_command
    target_label: command
  - replacement: 10.5.66.4:9275
    target_label: __address__
  - replacement: ub/0
    target_label: juju_unit
  - replacement: ub
    target_label: juju_application
  scrape_interval: 5m
  scrape_timeout: 30s
  static_configs:
  - labels:
      dns_name: juju-0a9b90-9.lxd
      host: 10.5.66.251
      juju_application: nrpe
      juju_model: welcome-lxd
      juju_model_uuid: 7f841a78-278e-4f12-8a42-688d600a9b90
      juju_unit: nrpe/0
    targets:
    - 10.5.66.251:5666
- forward_alert_rules: true
  job_name: juju_welcome-lxd_7f841a7_cp_prometheus_scrape
  relabel_configs:
  - regex: (.*)
    separator: _
    source_labels:
    - juju_model
    - juju_model_uuid
    - juju_application
    - juju_unit
    target_label: instance
  scrape_interval: 5m
  scrape_timeout: 30s
  static_configs:
  - labels:
      dns_name: juju-0a9b90-8.lxd
      host: 10.5.66.4
      juju_application: cp
      juju_model: welcome-lxd
      juju_model_uuid: 7f841a78-278e-4f12-8a42-688d600a9b90
      juju_unit: cp/0
    targets:
    - 10.5.66.4:9090
```

The incoming relation data to scrape-config does not include `forward_alert_rules`, but it is present in the relation data incoming into prometheus:
```bash
juju show-unit prometheus/0
```
```diff
prometheus/0:
  workload-version: 2.52.0
  opened-ports: []
  charm: ch:amd64/prometheus-k8s-232
  leader: true
  life: alive
  relation-info:
  - relation-id: 30
    endpoint: metrics-endpoint
    related-endpoint: metrics-endpoint
    application-data:
      alert_rules: '{"groups": "..."}'
      scrape_jobs: '[{
        "job_name": "juju_welcome-lxd_7f841a7_ub_0_check_conntrack_prometheus_scrape",
        "static_configs": [...],
        "relabel_configs": [...],
        "params": {"command": ["check_conntrack"], "ssl": [true]},
        "metrics_path": "/export",
+       "forward_alert_rules": true,
        "scrape_interval":"5m", 
        "scrape_timeout": "30s"}, ...
      ]'
```

- @selcem-artan reported using scrape-config rev58, and there aren't notable [changes recently](https://github.com/canonical/prometheus-scrape-config-k8s-operator/compare/rev58...rev62).
- In rev58, prometheus_scrape has `LIBPATCH = 50`, and there aren't notable [changes recently](https://github.com/canonical/prometheus-k8s-operator/compare/rev237...rev243#diff-3eb4f4fb71ab351956c8e7b96b07a804995e81540a0d2e94c2f63333c7792f79).

The issue is that in prometheus-scrape-config we blindly take all config options as scrape configs, and recently we added a new config option, `forward_alert_rules`, which is an unrelated, and therefore not a valid scrape config key.
