### ISSUE TITLE
Improve readability of NRPE alert titles

### ISSUE THREAD

**Issue by przemeklal** [canonical/cos-proxy-operator#86]
### Enhancement Proposal

Titles of NRPE alerts coming from cos-proxy are very long and difficult to read once they end up in tools like PagerDuty, especially in the environments that use long Nagios host context values and long hostnames, for example:

```
[FIRING:1] xxxxxxxxx-yyyyyyyyyy-zzzzzzzzzzzz-site-longhostname OpenStack
00000000-00000000-00000000-00000000 xxxxxxxxx-yyyyyyyyyy-zzzzzzzzzzzz-site-longhostname
(CheckNtpmonNrpeAlert check_ntpmon brxyz.longhostname.maas 10.256.256.1 10.256.256.1:5666
juju_openstack_1234567_xxxxxxxxx_yyyyyyyyyy_zzzzzzzzzzzz_site_longhostname_check_ntpmon_prometheus_scrape
remote-00000000000000000000000000000000 remote-00000000000000000000000000000000/2 critical)
```

The data is anonymised of course but I kept the original length of each string.

As an operator, I find many parts of the title unhelpful, especially:
- remote app and unit names: remote-00000000000000000000000000000000 and remote-00000000000000000000000000000000/2 aren't very useful for human operators
- repeated host IP and NRPE endpoint: 10.256.256.1 10.256.256.1:5666, there's also an FQDN there
- juju model uuid 00000000-00000000-00000000-00000000 doesn't need to be in the title (in my opinion)
- hostname is repeated at least 3 times
 
The same alert title looks like this when it's sent by Nagios:

```
CRITICAL: 'xxxxxxxxx-yyyyyyyyyy-zzzzzzzzzzzz-site-longhostname-check_ntpmon' on 'xxxxxxxxx-yyyyyyyyyy-zzzzzzzzzzzz-site-longhostname'
```

It's not _perfect_ but it gives me all the necessary information.

An example of a leaner NRPE alert title coming from COS Proxy that is much more readable:

```
[FIRING:1] xxxxxxxxx-yyyyyyyyyy-zzzzzzzzzzzz-site-longhostname CheckNtpmonNrpeAlert critical
```

All the extra details could be still available in the alert description.

I believe it's worth to start a discussion.

**Comment by sed-i** [comment]
After discussing with @marcusboden, 
- When alerts are rendered, e.g. on PagerDuty, the title should be shorter and the expr is not needed
- Something between prometheus and pagerduty, all labels key_value get concatenated into the alert's summary, which adds quite a bit to the total length. Perhaps it's because the alertmanager config has a "group_by" that includes multiple labels.
- The raw event details (`description` key) on pagerduty that comes from alertmanager is alerady too verbose. But that description key is not the same as the alert rule description.

### Possible solutions
- Shift the deduplication logic into the group name, instead of alertname, assuming prometheus would not collide on this.
- Test if alert names collide at all if they are coming from different files or groups.
- Compare how alerts are rendered on Pushover
- See if we can customize alertmanager's pagerduty's settings section. In particular the `description` template.

**Comment by lucabello** [comment]
Related link: https://community.pagerduty.com/forum/t/prometheus-how-can-i-format-the-summary-flied/3787/2

**Comment by lucabello** [comment]
You can modify the title field you see in the alert in PagerDuty through the alertmanager config. The field to do that is `pagerduty_configs`, as shown in the [alertmanager docs](https://prometheus.io/docs/alerting/latest/configuration/#pagerduty_config); you can use Go templating to define what you want the string to look like; an example of that is in the previous comment (again, [here](https://community.pagerduty.com/forum/t/prometheus-how-can-i-format-the-summary-flied/3787/2)).

We set up a successful test with the following alertmanager configuration:
```yaml
global:
  http_config:
    tls_config:
      insecure_skip_verify: true
receivers:
- name: pagerduty
  pagerduty_configs:
  - routing_key: <routing_key>
    description: "{{ range .Alerts }}{{ .Labels.alertname }}{{ end }}"
- name: dummy
  webhook_configs:
  - url: http://127.0.0.1:5001/
route:
  group_by:
  - juju_unit
  - juju_model_uuid
  - juju_model
  - check
  - juju_application
  group_interval: 5m
  group_wait: 30s
  receiver: dummy
  repeat_interval: 1h
  routes:
  - matchers:
    - integration!=webhook
    - alertname!=Watchdog
    receiver: pagerduty

```

The example uses `{{ .Labels.alertname }}`, but you can actually use any Label or Annotation that shows up in PagerDuty.

Additionally, you can add extra fields to the details by adding:
```yaml
pagerduty_configs:
  details:
    custom_field: "custom data"
```
You can use Go templates here as well; look at the previous links for more details.

**Comment by lucabello** [comment]
You can test the deployment easily by deploying Prometheus, Avalanche, and Alertmanager; use this bundle!

```yaml
bundle: kubernetes
applications:
  alertmanager:
    charm: alertmanager-k8s
    channel: edge
    revision: 95
    resources:
      alertmanager-image: 83
    scale: 1
    constraints: arch=amd64
    storage:
      data: kubernetes,1,1024M
    trust: true
  avalanche:
    charm: avalanche-k8s
    channel: edge
    revision: 35
    resources:
      avalanche-image: 17
    scale: 1
    constraints: arch=amd64
    trust: true
  prometheus:
    charm: prometheus-k8s
    channel: edge
    revision: 154
    resources:
      prometheus-image: 131
    scale: 1
    constraints: arch=amd64
    storage:
      database: kubernetes,1,1024M
    trust: true
relations:
- - alertmanager:alerting
  - prometheus:alertmanager
- - prometheus:metrics-endpoint
  - avalanche:metrics-endpoint
```
