### ISSUE TITLE
Alert rules for NRPE are not created for all units

### ISSUE THREAD

**Issue by guimaluf** [canonical/cos-proxy-operator#99]
### Bug Description

While paring LMA and COS alerts we noticed that alert rules for nrpe are not created for all units, only a few (one per nrpe application, instead of one per nrpe unit).

### To Reproduce

```
juju status --relations 
...
cos-proxy-monitors:downstream-prometheus-scrape                      cos-scrape-interval-config:configurable-scrape-jobs  prometheus_scrape               regular
nrpe-compute:monitors                                                cos-proxy-monitors:monitors                          monitors                        regular      
nrpe-container:monitors                                              cos-proxy-monitors:monitors                          monitors                        regular      
nrpe-control-node:monitors                                           cos-proxy-monitors:monitors                          monitors                        regular      
nrpe-storage:monitors                                                cos-proxy-monitors:monitors                          monitors                        regular      
...
```

Show the metrics for all the units from the related application but not for the `_alert_rules`
```
juju show-unit scrape-interval-config/0
```

Remove and relate again 
```
juju remove-relation cos-proxy-monitors:downstream-prometheus-scrape cos-scrape-interval-config:configurable-scrape-jobs
juju relate cos-proxy-monitors:downstream-prometheus-scrape cos-scrape-interval-config:configurable-scrape-jobs
```

No sign of alerts_rules for every unit
```
juju show-unit scrape-interval-config/0 | grep alert_rules
```

### Environment

```
juju --version 
2.9.45-ubuntu-amd64

App                        Version                  Charm                         Channel
alertmanager               0.25.0                   alertmanager-k8s              stable
catalogue                  active                   stable                        19
grafana                    9.2.1                    grafana-k8s                   stable
loki                       2.7.4                    loki-k8s                      stable
prometheus                 2.43.0                   prometheus-k8s                stable
scrape-interval-config     n/a                      prometheus-scrape-config-k8s  latest/edge
traefik                    2.9.6                    traefik-k8s                   stable
```

### Relevant log output

```shell
n/a
```

**Comment by przemeklal** [comment]
Additionally, we don't see any missing nrpe targets in vector's nrpe_lookup.csv on the cos-proxy-monitors unit and metrics from all nrpe targets metrics appear in Prometheus. Only alert rules are missing (we're talking about rules from 3 units present vs 80-ish units missing).

**Comment by peppepetra** [comment]
In my view, if cos-proxy is able to add a label to each exported metric like "origin=nrpe-exporter"  or sth similar and juju_model is added by default we can simply have one single alert for each model which works for any nrpe exported metric 

```
alert: NrpeExporterAlert
expr: |
  label_replace(avg_over_time(command_status{juju_model="openstack", origin="nrpe-exporter"}[15m]), "check", "$1", "job", ".*.(check_.*)_prometheus_scrape") > 1.3
for: 0m
labels:
  severity: critical # would be beneficial if we can have that depending on the value to catch severity in PD 
annotations:
  summary:  Unit {{ $labels.juju_unit }} command {{ $labels.check }} critical or unknown
  description: |
    Check provided by nrpe_exporter in model {{ $labels.juju_model }}
   
      Unit = {{ $labels.juju_unit }}
 
      Failing check = {{ $labels.check }}

      Value = {{ $value }}

      Legend for Value:
      StatusOK       = 0
      StatusWarning  = 1
      StatusCritical = 2
      StatusUnknown  = 3
```

**Comment by przemeklal** [comment]
We seem to have one env affected this badly, there's a chance that this happens only after cos-proxy upgrades/redeployments.

We did an experiment:
1. Removed cos-proxy-monitors <-> scrape-interval-config relation.
2. Removed the consumed offer in the OpenStack model, removed the offer in the cos model.
3. Removed scrape-interval-config application. At this stage, all old alert rules provided by cos-proxy-monitors are still visible in Prometheus, there's no cleanup!
4. Redeployed scrape-interval-config in the COS model, re-created the offer and re-created the relation with cos-proxy-monitors.
5. In the result, cos-proxy-monitors doesn't write any relation data into the downstream-prometheus-scrape, application-data is empty:
```
scrape-interval-config/0:
  workload-version: n/a
  opened-ports: []
  charm: ch:amd64/focal/prometheus-scrape-config-k8s-39
  leader: true
  life: alive
  relation-info:
  - relation-id: 54
    endpoint: metrics-endpoint
    related-endpoint: metrics-endpoint
    application-data: {}
    related-units:
      prometheus/0:
        in-scope: true
        data:
          egress-subnets: redacted/32
          ingress-address: redacted
          private-address: redacted
  - relation-id: 55
    endpoint: configurable-scrape-jobs
    cross-model: true
    related-endpoint: downstream-prometheus-scrape
    application-data: {}
    related-units:
      remote-5eb88f1eccec4a5d8b85b5883b969e15/1: # this is cos-proxy-monitors
        in-scope: true
        data:
          egress-subnets: redacted/32
          ingress-address: redacted
          private-address: redacted
  provider-id: scrape-interval-config-0
  address: redacted

```

All nrpe targets show up fine in nrpe_lookup.csv, prometheus scrapes vector without any issues, metrics seem to be complete. My wild guess is that the cos-proxy charm assumes that all nrpe targeted have been processed already, based on the information in the stored state, and decides not to update any alert rules but this would need to be confirmed.
